### ISSUE TITLE
[meta] Add test

### ISSUE THREAD

**Issue by rgaiacs** [CRICDatabase/searchable-image-database-nodejs#105]
# DAO

# REST API

- [ ] https://github.com/CRICDatabase/searchable-image-database-nodejs/issues/106
- [ ] https://github.com/CRICDatabase/searchable-image-database-nodejs/issues/107
- [ ] https://github.com/CRICDatabase/searchable-image-database-nodejs/issues/108
- [ ] https://github.com/CRICDatabase/searchable-image-database-nodejs/issues/109
- [ ] https://github.com/CRICDatabase/searchable-image-database-nodejs/issues/110
